"""Migração inicial

Revision ID: 12d82a9ee220
Revises: 
Create Date: 2024-11-19 13:47:00.128388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d82a9ee220'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('instituicao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artigo',
    sa.Column('id_artigo', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('id_autor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['autor.id'], ),
    sa.PrimaryKeyConstraint('id_artigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artigo')
    op.drop_table('autor')
    # ### end Alembic commands ###
